name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-generated-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: pnpm build
      - name: Check for uncommitted changes after build
        run: |
          git update-index --assume-unchanged pnpm-lock.yaml
          if ! git diff --exit-code; then
            echo 'Build produced uncommitted changes (excluding lock file). Please run pnpm build and commit the results.'
            git diff
            exit 1
          fi
          git update-index --no-assume-unchanged pnpm-lock.yaml

  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run Prettier check
        run: pnpm prettier --check .

  test:
    runs-on: ubuntu-latest
    env:
      PORT: 3001
      NODE_ENV: development
      SIG_ETH_RPC_URL_SEPOLIA: ${{ secrets.SIG_ETH_RPC_URL_SEPOLIA }}
      SIG_ETH_RPC_URL_MAINNET: ${{ secrets.SIG_ETH_RPC_URL_MAINNET }}
      SIG_EVM_SK_1: ${{ secrets.SIG_EVM_SK_1 }}
      SIG_EVM_SK_2: ${{ secrets.SIG_EVM_SK_2 }}
      SIG_EVM_SK_3: ${{ secrets.SIG_EVM_SK_3 }}
      SIG_EVM_SK_4: ${{ secrets.SIG_EVM_SK_4 }}
      SIG_EVM_SK_5: ${{ secrets.SIG_EVM_SK_5 }}
      SIG_SOL_RPC_URL_DEV: ${{ secrets.SIG_SOL_RPC_URL_DEV }}
      SIG_SOL_RPC_URL_MAINNET: ${{ secrets.SIG_SOL_RPC_URL_MAINNET }}
      SIG_SOL_SK: ${{ secrets.SIG_SOL_SK }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Print env (debug)
        run: env | grep SIG_ || true
      - name: Run tests
        run: pnpm test
